main: me.rayzr522.survivalcore.SurvivalCore
name: SurvivalCore
version: 1.0.0
description: A core plugin like Essentials, but with less game-changing features
author: Rayzr
commands:
  survivalcore:
    description: The main command for SurvivalCore